###
GET https://book-api-854460623550.asia-southeast2.run.app/api/categories
 
###
POST http://localhost:3000/api/categories
Content-Type: application/json

{
    "name": "Fiksi",
    "description": "Buku-buku fiksi populer"

}

###
PATCH http://localhost:3000/api/categories/NJxk92Fbp6fvNMAsYhrU
Content-Type: application/json

{
    "name": "Astronomi",
    "description": "Buku-buku astronomi"

}

###
DELETE http://localhost:3000/api/categories/q8FcuKlXndz9i24K82VD

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
     "title": "Harry Potter dan Batu Bertuah",
     "author": "J.K. Rowling",
     "publicationDate": "1997-06-26",
     "publisher": "Gramedia",
     "pages": 320,
     "isbn": "9780747532743",
     "categoryId": "NJxk92Fbp6fvNMAsYhrU"

}

###
POST http://localhost:3000/api/books
Content-Type: application/json

{
     "title": "Tutorial Limit",
     "author": "Mbak Hila",
     "publicationDate": "2023-12-12",
     "publisher": "Gramedia",
     "pages": 440,
     "categoryId": "NJxk92Fbp6fvNMAsYhrU"

}


###
GET https://book-api-854460623550.asia-southeast2.run.app/api/books

###
PATCH http://localhost:3000/api/books/sxDc1pmGWxCJtw25MPtd
Content-Type: application/json

{
     "title": "Kalkulus",
     "author": "Hammam",
     "publicationDate": "2000-12-09",
     "publisher": "Gramedia",
     "pages": 320,
     "isbn": "9780747532743",
     "categoryId": "NJxk92Fbp6fvNMAsYhrU"

}

###
DELETE http://localhost:3000/api/books/hlhvLsSOHfpyEbjySelE