###
POST  http://localhost:3000/api/categories
Content-Type: application/json

{
    "name" : "Teknologi",
    "description": "Buku - buku tentang teknologi dan komputer"
}

###
POST  http://localhost:3000/api/categories
Content-Type: application/json

{
    "name" : "Sejarah",
    "description": "Sejarah Kebudayaan Indonesia"
}

###

###
GET http://localhost:3000/api/categories/2

###
PATCH   http://localhost:3000/api/categories/2
Content-Type: application/json

{
    "name" : "Science",
    "description": "Natural, applied, and fiction"
}

###
DELETE http://localhost:3000/api/categories/2

###
GET http://localhost:3000/api/books

###
POST http://localhost:3000/api/books
Content-Type: application/json


{
     "title": "Belajar Node.js",
     "author": "Andi",
     "publicationDate": "2024-04-18",
     "publisher": "Penerbit Maju",
     "pages": 200,
     "isbn": "978-0-061-96436-7",
     "coverImage": "https://example.com/cover.jpg",
     "categoryId": 1
}

###
POST http://localhost:3000/api/books
Content-Type: application/json


{
     "title": "Belajar Python",
     "author": "hammam",
     "publicationDate": "2000-03-12",
     "publisher": "Penerbit Andi",
     "pages": 200,
     "categoryId": 1
}

###
POST http://localhost:3000/api/books
Content-Type: application/json


{
     "title": "Belajar Fisika",
     "author": "fadhiel",
     "publicationDate": "2023-09-23",
     "publisher": "Penerbit Andi",
     "pages": 400,
     "categoryId": 3
}

###
PATCH http://localhost:3000/api/books/4
Content-Type: application/json


{
     "title": "Belajar Sejarah",
     "author": "Nasywa",
     "publicationDate": "2000-09-14",
     "publisher": "Penerbit MBZ",
     "pages": 900,
     "categoryId": 3
}

###
DELETE http://localhost:3000/api/books/2

###
GET http://localhost:3000/api/books

###
GET http://localhost:3000/api/books?publicationDate=2024-04-18